schema: spec-driven

context: |
  Package manager: uv
  Testing framework: pytest, pytest-cov
  We use conventional commits

rules:
  specs:
    - |
      When a spec is archived, corresponding spec.md formats must be produced under openspec/specs. These sepc.md
      files must contain a header like "# {spec name} Specification" and headings for "## Purpose" and ## Requirements".
